version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - timescaledb
      - kafka
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: tradingapp
      POSTGRES_PASSWORD: tradingapp
      POSTGRES_DB: tradingapp
    ports:
      - "5432:5432"
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    environment:
      POSTGRES_USER: tradingapp
      POSTGRES_PASSWORD: tradingapp
      POSTGRES_DB: marketdata
    ports:
      - "5433:5432"
  kafka:
    image: bitnami/kafka:latest
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"
